image:
  name: wunderwerk/node:lts
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

definitions:
  steps:
    - step: &lint
        name: Lint
        runs-on: self.hosted
        script:
          - pnpm install

          - pnpm typecheck
          - pnpm lint
        caches:
          - node
    - step: &test
        name: Test
        runs-on: self.hosted
        script:
          - pnpm install

          - pnpm test
        caches:
          - node

pipelines:
  default:
    - parallel:
      - step: *lint
      - step: *test
