name: Lint & Test

on:
  push: 
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Code Style
        run: pnpm exec biome ci

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test